### ISSUE TITLE
Impossible d'installer Cagette

### ISSUE THREAD

**Issue by papaeng89** [CagetteNet/cagette#140]
Bonjour,

Nous souhaitons installer l'application Cagette sur un de nos serveurs, il y a eu beaucoup de changement depuis 3 ans. Le wiki n'est plus à jour et impossible d'installer l'application car il manque des pré-requis. 

Page obsolète : https://wiki.cagette.net/dev:install_dev
Page obsolète : https://wiki.cagette.net/dev:install_neko

Nous voudrions offrir une plateforme locale pour nos producteurs locaux car les marchés sont fermés et en période de confinement,

Merci de votre aide

Christophe

**Comment by bablukid** [comment]
Bonjour,
Nous ne sommes pas en mesure de t'aider car effectivement les pages ne sont plus à jour, et l'install est vraiment complexe à faire.

Nous sommes déjà débordé en temps normal, et là vu le contexte encore plus.

Le plus simple est d'utiliser notre site officiel app.cagette.net , ça ne craint rien pour vos données ( https://www.cagette.net/donnees-personnelles/ )

**Comment by papaeng89** [comment]
Bonjour François,

Merci de ta réponse rapide, c'est vraiment dommage. 
Courage à vous et votre équipe

Christophe DANIEL
