### ISSUE TITLE
Invalid field access sur sauvegarde d'un formulaire

### ISSUE THREAD

**Issue by ValerianSo** [CagetteNet/cagette#141]
A plusieurs reprises, quand je sauvegarde un formulaire, j'obtiens l'erreur "Invalid field access"
La dernière que j'ai eu est sur l'édition des coordonnées d'un membre, avec  : "Invalid field access: substr".
La première fois c'était sur l'édition des détails d'un produit.
Une piste: les produits, comme les membres, je les ai importé par fichier CSV. Le problème semble donc survenir avec les données importées. Et pour le produit que j'éditais qui a posé problème, c'était le seul pour lequel j'avais rempli la colonne "Stock".

**Comment by ValerianSo** [comment]
Pour reproduire si vous avez accès à mon Cagette, c'est "AMAP de la Lande au Pigeon Blanc" (https://app.cagette.net/user/choose?group=5527)
et avec l'URL https://app.cagette.net/member/edit/125164 pour le membre.
Une fois entré en édition sur la fiche, ne rien modifier et cliquer sur OK, l'erreur se déclenche.

**Comment by ValerianSo** [comment]
Ah, je viens de voir sur Facebook les problèmes de surcharge serveur, qui pourrait expliquer ce comportement...

**Comment by bablukid** [comment]
Bonjour, le bug "Invalid field access: substr" est corrigé, bonne journée
