### ISSUE TITLE
page /dev:install_dev, besoin de précision sur "Installation des dépendences"

### ISSUE THREAD

**Issue by pfxx** [CagetteNet/cagette#143]
Bonjour,

J'essaie d'installer un env de dév selon https://wiki.cagette.net/dev:install_dev

Chapitre "Installation des dépendences"  
```
cd projBack
make install ENV=dev
cd ../projFront 
```

ces répertoires n'existent pas (plus) sous les sources ./cagette, par contre il y a 
* backend (mais il ne contient pas de Makefile)
* frontend

Y aurait il un problème avec cette doc ? y a t il une doc + à jour

Merci

**Comment by bablukid** [comment]
Bonjour, je suis désolé mais la doc n'est pas du tout à jour.
nous sommes actuellement submergés, donc elle n'est pas prête d'etre à jour.

**Comment by pfxx** [comment]
ok, je reviendrai plus tard (c'était pour donner un coup de main)
