### ISSUE TITLE
Documentation Environnement de développement obsolète

### ISSUE THREAD

**Issue by zegratman** [CagetteNet/cagette#144]
Bonjour,

J'ai essayé de suivre les instructions pour la mise en place d'un environnement de développement afin de contribuer, sans succès:
- Liens obsolètes (plus de cagette.tar ou cagette-php.tar)
- Nom des dossiers dans le projet git incohérents (projBack > backend, par exemple)
- Instructions incomplètes (commandes de compilation de fonctionnent pas)
- Erreurs de compilation NPM

Bref, je pense que ce projet est parti dans une dimension qui ne relève plus de l'open source, et l'obscurantisme qui entoure les sources et sa documentation poussent largement à la solution "payante".

Honte à vous.

**Comment by bablukid** [comment]
facile de critiquer les autres, ton compte github est quasi vide, visiblement tu ne participes , ni n'aides aucun projet. 
Moi ça fait 6 ans que je commite du code de manière ouverte sur ce projet.
Ce n'est pas parce qu'on ouvre son code que l'on est obligé de rédiger toute la doc et de venir en aide à n'importe qui.  
Je ne supporte pas cette attitude.
